# Generated by Django 5.0.6 on 2024-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movieselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='movieselection',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='movieselection',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
