# Generated by Django 5.0.6 on 2024-11-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieselection',
            name='time',
        ),
        migrations.AddField(
            model_name='movieselection',
            name='horaire',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='main.horaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horaire',
            name='name',
            field=models.CharField(default='17h30', max_length=8),
        ),
        migrations.AlterField(
            model_name='movieselection',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
    ]
