# Generated by Django 5.0.6 on 2024-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_movieselection_time_movieselection_horaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieselection',
            name='movie_name',
            field=models.CharField(max_length=255),
        ),
    ]
