# Generated by Django 5.0.6 on 2024-11-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movieselection_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieselection',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
    ]
