# Generated by Django 5.0.6 on 2024-11-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_movieselection_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieselection',
            name='ticket_price',
        ),
    ]
